<?php
$companies = array(
1 => array('value' => 1, 'title' => 'AKORT'),
2 => array('value' => 2, 'title' => 'Auchan'),
3 => array('value' => 3, 'title' => 'Avoska'),
4 => array('value' => 4, 'title' => 'Bacardi'),
5 => array('value' => 5, 'title' => 'Baltika Breweries'),
6 => array('value' => 6, 'title' => 'Beiersdorf'),
7 => array('value' => 7, 'title' => 'Billa'),
8 => array('value' => 8, 'title' => 'Coca-Cola'),
9 => array('value' => 9, 'title' => 'Colgate-Palmolive'),
10 => array('value' => 10, 'title' => 'Danone - Unimilk Group of Companies'),
11 => array('value' => 11, 'title' => 'Diageo'),
12 => array('value' => 12, 'title' => 'DIXY Group'),
13 => array('value' => 13, 'title' => 'Dr.Oetker'),
14 => array('value' => 14, 'title' => 'EFES'),
15 => array('value' => 15, 'title' => 'Ferrero Russia'),
16 => array('value' => 16, 'title' => 'FM Logistic Vostok'),
17 => array('value' => 17, 'title' => 'Gradient'),
18 => array('value' => 18, 'title' => 'Hyperglobus'),
19 => array('value' => 19, 'title' => 'Imperial Tobacco Sales and Marketing'),
20 => array('value' => 20, 'title' => 'Japan Tobacco Internation (JTI)'),
21 => array('value' => 21, 'title' => 'Johnson&Johnson'),
22 => array('value' => 22, 'title' => 'Kimberly-Clark'),
23 => array('value' => 23, 'title' => 'Lenta'),
24 => array('value' => 24, 'title' => 'L’Oreal'),
25 => array('value' => 25, 'title' => 'Mareven Food Central'),
26 => array('value' => 26, 'title' => 'Mars'),
27 => array('value' => 27, 'title' => 'Media Markt'),
28 => array('value' => 28, 'title' => 'Metro Cash& Carry'),
30 => array('value' => 30, 'title' => 'Mon’delez Rus LLC'),
31 => array('value' => 31, 'title' => 'M.Video'),
32 => array('value' => 32, 'title' => 'Nestle Rossiya LLC'),
33 => array('value' => 33, 'title' => 'NEVA CHEESES'),
34 => array('value' => 34, 'title' => 'O’KEY'),
35 => array('value' => 35, 'title' => 'Olivier'),
36 => array('value' => 36, 'title' => 'Paulig'),
37 => array('value' => 37, 'title' => 'PepsiCo'),
38 => array('value' => 38, 'title' => 'Pernod Ricard Rouss'),
39 => array('value' => 39, 'title' => 'Petelino'),
40 => array('value' => 40, 'title' => 'Procter&Gamble'),
41 => array('value' => 41, 'title' => 'Productgarant'),
42 => array('value' => 42, 'title' => 'RusBrand'),
43 => array('value' => 43, 'title' => 'SunInBev'),
44 => array('value' => 44, 'title' => 'S.C.Johnson and Son'),
45 => array('value' => 45, 'title' => 'Schwarzkopf & Henkel'),
46 => array('value' => 46, 'title' => 'SDC-Foods'),
47 => array('value' => 47, 'title' => 'SELGROS Cash&Carry'),
48 => array('value' => 48, 'title' => 'SPAR RUSSIA'),
49 => array('value' => 49, 'title' => 'Unilever'),
50 => array('value' => 50, 'title' => 'Union of independent retail chains of Russia'),
51 => array('value' => 51, 'title' => 'United Confectioners'),
52 => array('value' => 52, 'title' => 'Valio'),
53 => array('value' => 53, 'title' => 'X5 Retail Group'),
54 => array('value' => 54, 'title' => 'Polimerbyt'),
);